name: DoubleA-Hub
version: ${version}
author: Andrew121410
main: com.andrew121410.mc.doubleahub.DoubleAHub
api-version: 1.21
depend:
  - WorldGuard
  - World1-6Utils
  - floodgate
libraries:
  - "com.fasterxml.jackson.core:jackson-annotations:${jacksonVersion}"
  - "com.fasterxml.jackson.core:jackson-core:${jacksonVersion}"
  - "com.fasterxml.jackson.core:jackson-databind:${jacksonVersion}"
  - "com.fasterxml.jackson.dataformat:jackson-dataformat-yaml:${jacksonVersion}"

commands:
  doubleahub:
    permission: doubleahub.use