name: DoubleA-Hub
version: 1.0
author: Andrew121410
main: com.andrew121410.mc.doubleahub.DoubleAHub
api-version: 1.17
depend:
  - WorldGuard
  - World1-6Utils
  - floodgate
libraries:
  - "com.fasterxml.jackson.core:jackson-annotations:2.13.4"
  - "com.fasterxml.jackson.core:jackson-core:2.13.4"
  - "com.fasterxml.jackson.core:jackson-databind:2.13.4"
  - "com.fasterxml.jackson.dataformat:jackson-dataformat-yaml:2.13.4"

commands:
  doubleahub:
    permission: doubleahub.use